# Generated by Django 5.2.13 on 2026-05-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0074_task_status_reasons_metric_watermarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradingtask",
            name="live_tick_stale_guard_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Skip strategy/order processing for live ticks older than live_tick_max_age_seconds while waiting for fresh stream data.",
            ),
        ),
    ]
