# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from autoforex.protobuf.task.v1 import task_service_pb2 as autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in autoforex/protobuf/task/v1/task_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/autoforex.task.v1.TaskService/GetHealth',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthResponse.FromString,
                _registered_method=True)
        self.ListServerInstances = channel.unary_unary(
                '/autoforex.task.v1.TaskService/ListServerInstances',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesResponse.FromString,
                _registered_method=True)
        self.StartBacktest = channel.unary_unary(
                '/autoforex.task.v1.TaskService/StartBacktest',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartBacktestRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.StartTrading = channel.unary_unary(
                '/autoforex.task.v1.TaskService/StartTrading',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartTradingRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/GetTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/autoforex.task.v1.TaskService/ListTasks',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.PauseTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/PauseTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.PauseTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ResumeTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/ResumeTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ResumeTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.StopTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/StopTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StopTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.RestartTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/RestartTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RestartTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.RecoverTask = channel.unary_unary(
                '/autoforex.task.v1.TaskService/RecoverTask',
                request_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RecoverTaskRequest.SerializeToString,
                response_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
                _registered_method=True)


class TaskServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServerInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartBacktest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthResponse.SerializeToString,
            ),
            'ListServerInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServerInstances,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesResponse.SerializeToString,
            ),
            'StartBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartBacktest,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartBacktestRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'StartTrading': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrading,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartTradingRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksResponse.SerializeToString,
            ),
            'PauseTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.PauseTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'ResumeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ResumeTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'StopTask': grpc.unary_unary_rpc_method_handler(
                    servicer.StopTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StopTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'RestartTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RestartTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
            'RecoverTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverTask,
                    request_deserializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RecoverTaskRequest.FromString,
                    response_serializer=autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'autoforex.task.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('autoforex.task.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/GetHealth',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServerInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/ListServerInstances',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListServerInstancesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/StartBacktest',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartBacktestRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/StartTrading',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StartTradingRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/GetTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.GetTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/ListTasks',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/PauseTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.PauseTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/ResumeTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.ResumeTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/StopTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.StopTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/RestartTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RestartTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/autoforex.task.v1.TaskService/RecoverTask',
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.RecoverTaskRequest.SerializeToString,
            autoforex_dot_protobuf_dot_task_dot_v1_dot_task__service__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
