# Generated by Django 5.2.7 on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0013_tickdata_latest_lookup_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketevent",
            name="execution_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Execution run UUID when this event is associated with a task.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marketevent",
            name="task_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="marketevent",
            name="task_type",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32),
        ),
        migrations.AddIndex(
            model_name="marketevent",
            index=models.Index(
                fields=["task_type", "task_id", "-created_at"],
                name="market_even_task_ty_a1967e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketevent",
            index=models.Index(
                fields=["task_type", "task_id", "execution_id", "-created_at"],
                name="market_even_task_ty_6daaa4_idx",
            ),
        ),
    ]
